public class DetallesTarea extends javax.swing.JFrame {

    Escalar escalar = new Escalar();
    private Usuario UsuarioActual=new Usuario();
    public Tarea actual;
    
    public void setTarea(Tarea aux){
        actual=aux;
        datos();
    }
    
    private void datos(){
        lblNombre.setText(actual.getNombre());
        lblDescripcion.setText(actual.getDescripcion());
        lblEstado.setText(actual.getEstado());
        lblPrioridad.setText(actual.getPrioridad());
        lblUsuario.setText(actual.getUsuarioAsignado());
        lblFecha.setText(actual.getDia()+" "+actual.getMes()+" "+actual.getYear());
    }
    public DetallesTarea() {
        initComponents();
        
        setLocationRelativeTo(null);
        escalar.escalarLabel(lblFondo, "\\imagenes\\fondo5.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRDetalles = new PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblPrioridad = new javax.swing.JLabel();
        BTCerrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRDetalles.setBackground(new java.awt.Color(255, 255, 255, 100));
        PRDetalles.setRoundBottomLeft(35);
        PRDetalles.setRoundBottomRight(35);
        PRDetalles.setRoundTopLeft(35);
        PRDetalles.setRoundTopRight(35);
        PRDetalles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Fecha de Entrega :");
        PRDetalles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 200, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Usuario Asignado :");
        PRDetalles.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(51, 51, 51));
        lblFecha.setText("1 Enero");
        PRDetalles.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 270, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Nombre :");
        PRDetalles.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 30));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(51, 51, 51));
        lblNombre.setText("Hacer un discurso");
        PRDetalles.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 390, 30));

        lblDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        lblDescripcion.setText("_______________________________");
        PRDetalles.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 480, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Descripcion :");
        PRDetalles.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 160, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Estado :");
        PRDetalles.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 100, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Prioridad :");
        PRDetalles.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 130, 30));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        lblUsuario.setText("Maria");
        PRDetalles.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 320, 30));

        lblEstado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblEstado.setForeground(new java.awt.Color(51, 51, 51));
        lblEstado.setText("En proceso");
        PRDetalles.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 310, 30));

        lblPrioridad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrioridad.setForeground(new java.awt.Color(51, 51, 51));
        lblPrioridad.setText("Media");
        PRDetalles.add(lblPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 290, 30));

        BTCerrar.setBackground(new java.awt.Color(255, 255, 255));
        BTCerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BTCerrar.setForeground(new java.awt.Color(102, 102, 102));
        BTCerrar.setText("Cerrar");
        BTCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCerrarActionPerformed(evt);
            }
        });
        PRDetalles.add(BTCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        getContentPane().add(PRDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCerrar;
    private PanelRound PRDetalles;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private static javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrioridad;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
