import java.io.File;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class EditarTarea extends javax.swing.JFrame {

    Escalar escalar = new Escalar();
    public Usuario usuario= new Usuario(0,null,null,null,null);
    public String userHome = "C:\\Users\\Cesia\\Desktop";
    private String direcTareas = userHome + "\\Taskflow\\Tareas";
    private String listaTareas = userHome + "\\Taskflow\\Tareas\\listaTareas.txt";
    private Usuario UsuarioActual = new Usuario();
    private String fileUsuarios = userHome + "\\Taskflow\\Usuarios.txt";
    public ArrayList<Usuario> listaUsuarios;
    public ArrayList<Tarea> listaBuscar;
    public int indice=0;
    public TareasActuales tareasActuales;
    
    public void listaTareas(ArrayList<Tarea> list){
        listaBuscar=new ArrayList<Tarea> (list);
    }
    
    public void setIndice(int i){
        indice=i;
        TareaActual();
    }
    
    public void TareaActual(){
        TF_Nombre.setText(listaBuscar.get(indice).getNombre());
        TF_Descripcion.setText(listaBuscar.get(indice).getDescripcion());
        String dia=String.valueOf(listaBuscar.get(indice).getDia());
        CBDia.setSelectedItem(dia);
        CBMes.setSelectedItem(listaBuscar.get(indice).getMes());
        CBEstado.setSelectedItem(listaBuscar.get(indice).getEstado());
        CBPrioridad.setSelectedItem(listaBuscar.get(indice).getPrioridad());
        CBAsignarUsuario.setSelectedItem(listaBuscar.get(indice).getUsuarioAsignado());
        String year=String.valueOf(listaBuscar.get(indice).getYear());
        CBYear.setSelectedItem(year);
    }
    
    public EditarTarea(TareasActuales tareasActuales) {
        initComponents();
        
        setLocationRelativeTo(null);
        escalar.escalarLabel(lblFondo, "\\imagenes\\fondo5.png");
        
        this.tareasActuales=tareasActuales;
        
        UsuarioActual=UsuarioActual.obtenerUsuarioActual();
        
        Usuario aux= new Usuario();
        File direcUsuarios = new File(fileUsuarios);
        listaUsuarios=aux.listaUsuarios(direcUsuarios);
        
        for (int a = 0; a < listaUsuarios.size(); a++) {
            CBAsignarUsuario.addItem(listaUsuarios.get(a).getUsuario());  // Agregar el nombre de usuario al ComboBox
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PRRegistro = new PanelRound();
        jLabel12 = new javax.swing.JLabel();
        CBMes = new javax.swing.JComboBox<>();
        BT_Cancelar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        TF_Descripcion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TF_Nombre = new javax.swing.JTextField();
        CBPrioridad = new javax.swing.JComboBox<>();
        CBEstado = new javax.swing.JComboBox<>();
        CBAsignarUsuario = new javax.swing.JComboBox<>();
        CBDia = new javax.swing.JComboBox<>();
        BT_EditarTarea = new javax.swing.JButton();
        CBYear = new javax.swing.JComboBox<>();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PRRegistro.setBackground(new java.awt.Color(255, 255, 255, 100));
        PRRegistro.setRoundBottomLeft(35);
        PRRegistro.setRoundBottomRight(35);
        PRRegistro.setRoundTopLeft(35);
        PRRegistro.setRoundTopRight(35);
        PRRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Descripcion :");
        PRRegistro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 160, 30));

        CBMes.setBackground(new java.awt.Color(255, 255, 255));
        CBMes.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        CBMes.setForeground(new java.awt.Color(102, 102, 102));
        CBMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        PRRegistro.add(CBMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 170, 40));

        BT_Cancelar.setBackground(new java.awt.Color(255, 255, 255));
        BT_Cancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BT_Cancelar.setForeground(new java.awt.Color(102, 102, 102));
        BT_Cancelar.setText("Cancelar");
        BT_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_CancelarActionPerformed(evt);
            }
        });
        PRRegistro.add(BT_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        PRRegistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 520, 10));
        PRRegistro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 520, 10));

        TF_Descripcion.setBackground(new java.awt.Color(0, 0, 0,0));
        TF_Descripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TF_Descripcion.setForeground(new java.awt.Color(51, 51, 51));
        TF_Descripcion.setBorder(null);
        TF_Descripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TF_DescripcionMousePressed(evt);
            }
        });
        PRRegistro.add(TF_Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 520, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Nombre :");
        PRRegistro.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, 30));

        TF_Nombre.setBackground(new java.awt.Color(255, 255, 255,0));
        TF_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TF_Nombre.setForeground(new java.awt.Color(51, 51, 51));
        TF_Nombre.setText("Nombre de la tarea");
        TF_Nombre.setBorder(null);
        TF_Nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TF_NombreMousePressed(evt);
            }
        });
        PRRegistro.add(TF_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 520, 40));

        CBPrioridad.setBackground(new java.awt.Color(255, 255, 255));
        CBPrioridad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CBPrioridad.setForeground(new java.awt.Color(102, 102, 102));
        CBPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioridad", "Baja", "Media", "Alta" }));
        PRRegistro.add(CBPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 150, 40));

        CBEstado.setBackground(new java.awt.Color(255, 255, 255));
        CBEstado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CBEstado.setForeground(new java.awt.Color(102, 102, 102));
        CBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Por hacer", "En progreso", "Completada" }));
        CBEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEstadoActionPerformed(evt);
            }
        });
        PRRegistro.add(CBEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 320, 200, 40));

        CBAsignarUsuario.setBackground(new java.awt.Color(255, 255, 255));
        CBAsignarUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CBAsignarUsuario.setForeground(new java.awt.Color(102, 102, 102));
        CBAsignarUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asignar Usuario" }));
        PRRegistro.add(CBAsignarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 290, 40));

        CBDia.setBackground(new java.awt.Color(255, 255, 255));
        CBDia.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        CBDia.setForeground(new java.awt.Color(102, 102, 102));
        CBDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        PRRegistro.add(CBDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, 40));

        BT_EditarTarea.setBackground(new java.awt.Color(255, 255, 255));
        BT_EditarTarea.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BT_EditarTarea.setForeground(new java.awt.Color(102, 102, 102));
        BT_EditarTarea.setText("Editar Tarea");
        BT_EditarTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_EditarTareaActionPerformed(evt);
            }
        });
        PRRegistro.add(BT_EditarTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        CBYear.setBackground(new java.awt.Color(255, 255, 255));
        CBYear.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        CBYear.setForeground(new java.awt.Color(102, 102, 102));
        CBYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        CBYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBYearActionPerformed(evt);
            }
        });
        PRRegistro.add(CBYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 90, 40));

        getContentPane().add(PRRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_CancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BT_CancelarActionPerformed

    private void BT_EditarTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_EditarTareaActionPerformed
        String nombreTarea = TF_Nombre.getText();         // Nombre de la tarea
        String descrip = TF_Descripcion.getText();             // Descripción
        String meses = (String) CBMes.getSelectedItem(); // Mes asignado
        String estados = (String) CBEstado.getSelectedItem(); // Estado
        String prioridades = (String) CBPrioridad.getSelectedItem();
        int dias=0;// Prioridad
        if(!CBDia.getSelectedItem().toString().equals("Dia"))
            dias = Integer.parseInt(CBDia.getSelectedItem().toString());    // Día asignado
        String usuarioAsignado = (String) CBAsignarUsuario.getSelectedItem(); // Usuario asignado
        int year=0;
        if(!CBYear.getSelectedItem().toString().equals("Año"))
            year = Integer.parseInt(CBYear.getSelectedItem().toString());  

        if(!nombreTarea.isEmpty() && !descrip.isEmpty() && !meses.equals("Mes") && !estados.equals("Estado") && !prioridades.equals("Prioridad") && !usuarioAsignado.equals("Asignar Usuario")){
            if(!CBDia.getSelectedItem().toString().equals("Dia") && !CBYear.getSelectedItem().toString().equals("Año")){
                Tarea nuevaTarea = new Tarea(listaBuscar.get(indice));
                nuevaTarea.setNombre(nombreTarea);
                nuevaTarea.setDescripcion(descrip);
                nuevaTarea.setMes(meses);
                nuevaTarea.setEstado(estados);
                nuevaTarea.setPrioridad(prioridades);
                nuevaTarea.setDia(dias);
                nuevaTarea.setUsuarioAsignado(usuarioAsignado);
                nuevaTarea.setYear(year);

                String direcTareaAct=direcTareas+"\\"+nuevaTarea.getNumeroTarea()+".txt";
                nuevaTarea.editarCualquierTarea(direcTareaAct,nuevaTarea,listaTareas,listaBuscar.get(indice),direcTareas);
                listaBuscar.set(indice, nuevaTarea);// Guardar en lista general
                tareasActuales.setLista();
                JOptionPane.showMessageDialog(null, "Tarea Editada");
                this.dispose();
            }else{
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
        }
    }//GEN-LAST:event_BT_EditarTareaActionPerformed

    private void TF_DescripcionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF_DescripcionMousePressed
        if(TF_Descripcion.getText().equals(listaBuscar.get(indice).getDescripcion())){
            TF_Descripcion.setText("");
        }
    }//GEN-LAST:event_TF_DescripcionMousePressed

    private void TF_NombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF_NombreMousePressed
        if(TF_Nombre.getText().equals(listaBuscar.get(indice).getNombre())){
            TF_Nombre.setText(" ");
        }
    }//GEN-LAST:event_TF_NombreMousePressed

    private void CBEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEstadoActionPerformed

    private void CBYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBYearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        TareasActuales tareasActuales= new TareasActuales();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarTarea(tareasActuales).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Cancelar;
    private javax.swing.JButton BT_EditarTarea;
    private javax.swing.JComboBox<String> CBAsignarUsuario;
    private javax.swing.JComboBox<String> CBDia;
    private javax.swing.JComboBox<String> CBEstado;
    private javax.swing.JComboBox<String> CBMes;
    private javax.swing.JComboBox<String> CBPrioridad;
    private javax.swing.JComboBox<String> CBYear;
    private PanelRound PRRegistro;
    private javax.swing.JTextField TF_Descripcion;
    private javax.swing.JTextField TF_Nombre;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblFondo;
    // End of variables declaration//GEN-END:variables
}
