
//version oficial 0.9
import java.io.*;
import java.awt.Color;
import java.util.ArrayList;

public class Login extends javax.swing.JFrame {

    private Escalar escalar = new Escalar();
    private String userHome = "C:\\Users\\Cesia\\Desktop";
    private String fileUsuarios = userHome + "\\Taskflow\\Usuarios.txt";
    public ArrayList<Usuario> lista; 

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        File Taskflow = new File(userHome+"\\Taskflow");
        if(!Taskflow.exists())
            creadorArchivos(userHome);
        setLocationRelativeTo(null);
        escalar.escalarLabel(jLabel2, "\\imagenes\\fondo1.jpg");
        escalar.escalarLabel(lblLogo, "\\imagenes\\logo.png");
        
        Usuario aux= new Usuario();
        File direcUsuarios = new File(fileUsuarios);
        lista=aux.listaUsuarios(direcUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelRound2 = new PanelRound();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelRound1 = new PanelRound();
        lblLogo = new javax.swing.JLabel();
        Aviso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TF_Usuario = new javax.swing.JTextField();
        BT_Inicio = new javax.swing.JButton();
        PF_Contraseña = new javax.swing.JPasswordField();
        PR_Salir = new PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(0, 0, 0, 200));
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelRound2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 10, 30));
        panelRound2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 100, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("    Registrarse");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        panelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 130, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("    Iniciar Sesion");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 130, 40));

        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 400, 40));

        panelRound1.setBackground(new java.awt.Color(0, 0, 0, 200));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 80, 80));

        Aviso.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        Aviso.setForeground(new java.awt.Color(102, 102, 255, 125));
        panelRound1.add(Aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 240, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" TASKFLOW");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));
        panelRound1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 277, 240, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contraseña:");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 120, 30));
        panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 240, 10));

        TF_Usuario.setBackground(new java.awt.Color(0, 0, 0, 0));
        TF_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TF_Usuario.setForeground(new java.awt.Color(102, 102, 102));
        TF_Usuario.setText("Ingrese su usuario");
        TF_Usuario.setBorder(null);
        TF_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TF_UsuarioMousePressed(evt);
            }
        });
        panelRound1.add(TF_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 240, 20));

        BT_Inicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BT_Inicio.setForeground(new java.awt.Color(102, 102, 102));
        BT_Inicio.setText("Iniciar Sesion");
        BT_Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BT_InicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BT_InicioMouseExited(evt);
            }
        });
        BT_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_InicioActionPerformed(evt);
            }
        });
        panelRound1.add(BT_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 130, 40));

        PF_Contraseña.setBackground(new java.awt.Color(0, 0, 0, 0));
        PF_Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PF_Contraseña.setForeground(new java.awt.Color(102, 102, 102));
        PF_Contraseña.setText("**********");
        PF_Contraseña.setBorder(null);
        PF_Contraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PF_ContraseñaMousePressed(evt);
            }
        });
        PF_Contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_ContraseñaActionPerformed(evt);
            }
        });
        panelRound1.add(PF_Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 240, -1));

        jPanel2.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 400, 390));

        PR_Salir.setBackground(new java.awt.Color(0, 0, 0,150));
        PR_Salir.setRoundBottomLeft(10);
        PR_Salir.setRoundBottomRight(10);
        PR_Salir.setRoundTopLeft(10);
        PR_Salir.setRoundTopRight(10);
        PR_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PR_SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PR_SalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PR_SalirMousePressed(evt);
            }
        });
        PR_Salir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("x");
        PR_Salir.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jPanel2.add(PR_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 40, 40));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_InicioActionPerformed
        Usuario act = new Usuario(TF_Usuario.getText(), PF_Contraseña.getText(), null, null);
        boolean acceso = false;
        int ind = -1;  // Usamos -1 para indicar que no hemos encontrado el usuario aún

        // Recorrer la lista de usuarios para verificar credenciales
        for (int aux = 0; aux < lista.size(); aux++) {  // Usamos lista.size() en lugar de lista.length
            if (lista.get(aux).getUsuario().equals(act.getUsuario()) && lista.get(aux).getContraseña().equals(act.getContraseña())) {
                acceso = true;
                ind = aux;  // Guardamos el índice del usuario encontrado
                break;  // Salimos del bucle una vez que se encuentra el usuario
            }
        }

        // Verificar si se encontró el usuario
        if (acceso && ind != -1) {
            act.guardarUsuarioActual(lista.get(ind));  // Usamos lista.get(ind) en lugar de lista[ind]

            // Abrir ventana correspondiente según el nivel del usuario
            if (lista.get(ind).getNivel().equals("base")) {
                InicioUsuario ventana = new InicioUsuario();
                ventana.setVisible(true);
                this.dispose();
            } else {
                Inicio ventana = new Inicio();
                ventana.setVisible(true);
                this.dispose();
            }
        } else {
            // Mostrar mensaje de error si no se encontró el usuario o si no coinciden los datos
            if (TF_Usuario.getText().equals("Ingrese su usuario") || PF_Contraseña.getText().equals("**********")) {
                Aviso.setText("*Ingrese los datos del usuario*");
            } else {
                Aviso.setText("*Usuario y/o contraseña incorrectos*");
            }
        }
    }//GEN-LAST:event_BT_InicioActionPerformed

    private void PR_SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PR_SalirMouseEntered
        Color color = new Color(237,181,94);
        PR_Salir.setBackground(color);
    }//GEN-LAST:event_PR_SalirMouseEntered

    private void TF_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TF_UsuarioMousePressed
        if(TF_Usuario.getText().equals("Ingrese su usuario")){
            TF_Usuario.setText("");
            TF_Usuario.setForeground(Color.LIGHT_GRAY);
        }
        if(String.valueOf(PF_Contraseña.getPassword()).isEmpty()){
            PF_Contraseña.setForeground(Color.GRAY);
            PF_Contraseña.setText("**********");
        }
    }//GEN-LAST:event_TF_UsuarioMousePressed

    private void PF_ContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PF_ContraseñaMousePressed
        if(PF_Contraseña.getText().equals("**********")){
            PF_Contraseña.setText("");
            PF_Contraseña.setForeground(Color.LIGHT_GRAY);
        }if(TF_Usuario.getText().isEmpty()){
            TF_Usuario.setForeground(Color.GRAY);
            TF_Usuario.setText("Ingrese su usuario");
        }
    }//GEN-LAST:event_PF_ContraseñaMousePressed

    private void BT_InicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_InicioMouseEntered
        Color color = new Color(237,181,94);
        BT_Inicio.setBackground(color);
        BT_Inicio.setForeground(Color.WHITE);
    }//GEN-LAST:event_BT_InicioMouseEntered

    private void BT_InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_InicioMouseExited
        BT_Inicio.setBackground(Color.LIGHT_GRAY);
        BT_Inicio.setForeground(Color.GRAY);
    }//GEN-LAST:event_BT_InicioMouseExited

    private void PR_SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PR_SalirMouseExited
        Color color = new Color(0,0,0,150);
        PR_Salir.setBackground(color);
    }//GEN-LAST:event_PR_SalirMouseExited

    private void PR_SalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PR_SalirMousePressed
        System.exit(0);
    }//GEN-LAST:event_PR_SalirMousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        Registro ventana = new Registro();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MousePressed

    private void PF_ContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_ContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF_ContraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    public static void creadorArchivos(String userHome){    
        File archivo = new File(userHome + "\\Taskflow");

        if (archivo.mkdir()) {
            System.out.println(".");
        } else {
            System.out.println("No se pudo crear la carpeta.");
        }

        File archivo1 = new File(userHome + "\\Taskflow\\Tareas");

        if (archivo1.mkdir()) {
            System.out.println(".");
        } else {
            System.out.println("No se pudo crear la carpeta.");
        }

        archivo = new File(userHome + "\\Taskflow\\Usuarios.txt");

        System.out.println(archivo.getAbsolutePath());

        try {
            if (archivo.createNewFile()) {
                System.out.println("Archivo creado en: " + archivo.getAbsolutePath());
            } else {
                System.out.println("El archivo ya existe en: " + archivo.getAbsolutePath());
            }
        } catch (IOException e) {
            System.out.println("Ocurrió un error al crear el archivo.");
            e.printStackTrace();
        }

        try (FileWriter writer = new FileWriter(archivo, true)) {
            writer.write("0 admin admin administrador admin\n");
            System.out.println("Usuario registrado correctamente");
        } catch (IOException e) {
            System.out.println("Error al escribir en el archivo: " + e.getMessage());
        }

        archivo = new File(userHome + "\\Taskflow\\UsuarioActual.txt");

        System.out.println(archivo.getAbsolutePath());

        try {
            if (archivo.createNewFile()) {
                System.out.println("Archivo creado en: " + archivo.getAbsolutePath());
            } else {
                System.out.println("El archivo ya existe en: " + archivo.getAbsolutePath());
            }
        } catch (IOException e) {
            System.out.println("Ocurrió un error al crear el archivo.");
            e.printStackTrace();
        }

        archivo = new File(userHome + "\\Taskflow\\Tareas\\ListaTareas.txt");
        try {
            if (archivo.createNewFile()) {
                System.out.println("Archivo creado en: " + archivo.getAbsolutePath());
            } else {
                System.out.println("El archivo ya existe en: " + archivo.getAbsolutePath());
            }
        } catch (IOException e) {
            System.out.println("Ocurrió un error al crear el archivo.");
            e.printStackTrace();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JButton BT_Inicio;
    private javax.swing.JPasswordField PF_Contraseña;
    private PanelRound PR_Salir;
    private javax.swing.JTextField TF_Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblLogo;
    private PanelRound panelRound1;
    private PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
